/* STAGE 5 — Luau, laid out for Rojo.
 *
 * In:  build/chunks.json, build/collision.json
 * Out: roblox/src/**.luau
 *
 * THIS IS WHERE METRES BECOME STUDS, and it is the only place in the pipeline
 * that knows about studs at all. Everything upstream works in the game's own
 * world metres, so changing CONFIG.studsPerM is a re-run of this stage — about
 * a second — rather than a re-bake. That is worth the discipline: the scale is
 * the number most likely to be wrong on the first attempt, and it is the one
 * you can only judge by standing a car next to a building and looking.
 *
 * FLAT NUMERIC ARRAYS, NOT TABLES OF TABLES. A chunk of 340 boxes as
 * {{x=..., y=..., size=...}, ...} is roughly six times the memory of a flat
 * array of numbers in Luau, and every one of those inner tables is a separate
 * allocation the GC then has to walk. At tens of thousands of parts across a
 * hundred chunks that is the difference between a stutter on chunk load and a
 * visible freeze. Seven numbers a box, documented at the top of each file.
 *
 * Usage: node tools/roblox/5-emit.mjs
 */
import { mkdirSync, writeFileSync, rmSync } from 'node:fs';
import { CONFIG } from './config.mjs';
import { makeLattice } from './lattice.mjs';
import { readFileSync } from 'node:fs';

const S = CONFIG.studsPerM;
const L = makeLattice(CONFIG);
const HEX = L.kind === 'hex';
const LV = CONFIG.voxel;                          // metres a level, both lattices
const LVS = LV * S;                               // and in studs

const CH = JSON.parse(readFileSync(`${CONFIG.out}/chunks.json`, 'utf8'));
const CO = JSON.parse(readFileSync(`${CONFIG.out}/collision.json`, 'utf8'));

const ROOT = 'roblox/src';
const dirs = [
  `${ROOT}/ReplicatedStorage/CityVisual/ChunkData`,
  `${ROOT}/ReplicatedStorage/Shared`,
  `${ROOT}/ServerScriptService/Data`
];
/* The chunk directory is wiped, not merged into. A bake with a smaller district
   leaves the previous run's outer chunks behind otherwise, and they load — so
   the city quietly keeps a ghost ring of the old slice around the new one,
   which is a genuinely baffling thing to debug from inside Studio. */
rmSync(`${ROOT}/ReplicatedStorage/CityVisual/ChunkData`, { recursive: true, force: true });
for (const d of dirs) mkdirSync(d, { recursive: true });

const R = v => Math.round(v * 1000) / 1000;       // a thousandth of a stud
const HDR = (what) =>
  `--!strict\n-- GENERATED by tools/roblox/5-emit.mjs -- do not edit by hand.\n` +
  `-- ${what}\n-- Rebuild with: node tools/roblox/bake.mjs\n\n`;

/* ---------------- palette ---------------- */
writeFileSync(`${ROOT}/ReplicatedStorage/CityVisual/Palette.luau`,
  HDR('Every colour in the city, deduplicated. Indices are 1-based (Luau).') +
  'return {\n' +
  CH.palette.map(c => `\tColor3.fromRGB(${c[0]}, ${c[1]}, ${c[2]}),`).join('\n') +
  '\n}\n');

/* ---------------- chunks ----------------

   A box is emitted as its CENTRE and its SIZE in studs, because that is what
   Roblox wants — a Part's CFrame is its centre — and converting on the client
   for thirty thousand parts is work done once here instead of on every device
   that ever loads the game.

   Ground sits at lattice level -1, so its centre lands at -M/2: the top face of
   the ground is exactly y = 0 and buildings stand on it rather than in it. */
let emitted = 0;
const index = [];
for (const c of CH.chunks) {
  const nums = [];
  for (const [a, l, b, sa, levels, sb, col] of c.boxes) {
    if (HEX) {
      /* A PRISM IS FIVE NUMBERS, not seven. Its footprint is always one hex of
         the same radius, so width and depth are global rather than per-part —
         which also means a hex chunk file is a third smaller than a box one at
         the same part count. */
      const [wx, wy] = L.centre(a, b);
      nums.push(R(wx * S), R((l + levels / 2) * LVS), R(wy * S), R(levels * LVS), col + 1);
    } else {
      const [x0, y0] = L.centre(a, b);
      const [x1, y1] = L.centre(a + sa - 1, b + sb - 1);
      nums.push(
        R((x0 + x1) / 2 * S), R((l + levels / 2) * LVS), R((y0 + y1) / 2 * S),
        R(sa * L.size * S), R(levels * LVS), R(sb * L.size * S),
        col + 1
      );
    }
  }
  emitted += c.boxes.length;
  const name = `Chunk_${c.cx}_${c.cz}`;
  index.push([c.cx, c.cz, c.boxes.length]);

  const stride = HEX ? 5 : 7;
  const rows = [];
  for (let i = 0; i < nums.length; i += stride)
    rows.push('\t' + nums.slice(i, i + stride).join(', ') + ',');

  writeFileSync(`${ROOT}/ReplicatedStorage/CityVisual/ChunkData/${name}.luau`,
    HDR(`Chunk (${c.cx}, ${c.cz}) -- ${c.boxes.length} parts.\n` +
        (HEX
          ? '-- Five numbers a prism: centreX, centreY, centreZ, height, paletteIndex.\n' +
            '-- The footprint is one hexagon of CityMeta.hexRadiusStuds, flat-to-flat\n' +
            '-- along X. Studs, world space, district centre at the origin.'
          : '-- Seven numbers a box: centreX, centreY, centreZ, sizeX, sizeY, sizeZ, paletteIndex.\n' +
            '-- Studs, world space, district centre at the origin.')) +
    'return {\n' + rows.join('\n') + '\n}\n');
}

/* ---------------- the chunk index ---------------- */
const half = CONFIG.half * S;
writeFileSync(`${ROOT}/ReplicatedStorage/CityVisual/CityMeta.luau`,
  HDR('What the client needs before it loads a single chunk.') +
  'return {\n' +
  `\tstudsPerMetre = ${S},\n` +
  `\tlattice = "${L.kind}",\n` +
  `\tlevelStuds = ${R(LVS)},\n` +
  (HEX ? `\thexRadiusStuds = ${R(L.size * S)},\n` : `\tvoxelStuds = ${R(L.size * S)},\n`) +
  `\tchunkStuds = ${R(CONFIG.chunkM * S)},\n` +
  `\thalfStuds = ${R(half)},\n` +
  `\tchunks = {\n` +
  index.map(([cx, cz, n]) => `\t\t{ ${cx}, ${cz}, ${n} },`).join('\n') +
  `\n\t},\n}\n`);

/* ---------------- collision ----------------

   Server-side, and the only geometry the physics engine ever sees. Six numbers
   a box; no colour, because nothing renders these. */
const cnums = [];
/* COLLISION STAYS SQUARE whatever the visual lattice is, and stage 4 rasterises
   it on its own CONFIG.voxel grid for that reason. These boxes are invisible:
   nobody can see that what stopped the car was a box rather than a hexagon, and
   boxes are several times cheaper because they merge in all three directions.
   The two agree to within half a cell, which is well inside the tolerance the
   driving model already has for the road mask. */
const CV = CONFIG.voxel * S;
for (const [x, z, sx, sz, y, sy] of CO.boxes) {
  cnums.push(
    R((x + sx / 2) * CV), R((y + sy / 2) * CV), R((z + sz / 2) * CV),
    R(sx * CV), R(sy * CV), R(sz * CV)
  );
}
const crows = [];
for (let i = 0; i < cnums.length; i += 6) crows.push('\t' + cnums.slice(i, i + 6).join(', ') + ',');
writeFileSync(`${ROOT}/ServerScriptService/Data/Collision.luau`,
  HDR(`${CO.boxes.length} building collision boxes.\n` +
      '-- Six numbers a box: centreX, centreY, centreZ, sizeX, sizeY, sizeZ. Studs.\n' +
      '-- These are the ONLY parts with CanCollide true. The voxel shell in\n' +
      '-- ReplicatedStorage.CityVisual is decoration and never enters a broadphase.') +
  'return {\n' + crows.join('\n') + '\n}\n');

/* ---------------- the drivable mask ----------------

   Shipped as base64 and decoded in Luau with buffer.fromstring, rather than as
   twenty thousand table entries. The cell size travels with it because the
   off-road constants in the driving model are tuned against it. */
writeFileSync(`${ROOT}/ReplicatedStorage/Shared/RoadMask.luau`,
  HDR('Where the tarmac is. One bit a cell, row-major from the south-west corner.\n' +
      '-- Decode: buffer.fromstring(base64decode(M.bits)); bit i is cell (i % span, i // span).\n' +
      '-- cellStuds matches W.cell (8 m) in the browser game, so the off-road\n' +
      '-- tuning in the driving model still means what it was tuned to mean.') +
  'return {\n' +
  `\tspan = ${CO.mask.span},\n` +
  `\tcellStuds = ${R(CO.mask.cell * S)},\n` +
  `\toriginStuds = ${R(-half)},\n` +
  /* AND THE SAME THING IN METRES, because the driving model is in metres.
     Every constant in drive() -- TOP_SPEED 100, STRAY_TOP 4.5, STRAY_TOL 10 --
     is metres and seconds, and the whole value of porting that model is that
     those numbers carry over unchanged. So the model asks this mask in metres
     and only the renderer multiplies by studsPerMetre. */
  `\tcellM = ${CO.mask.cell},\n` +
  `\toriginM = ${-CONFIG.half},\n` +
  `\tbits = "${CO.mask.bits}",\n` +
  '}\n');

/* ---------------- the minimap ---------------- */
writeFileSync(`${ROOT}/ReplicatedStorage/Shared/Minimap.luau`,
  HDR('A picture of the district, two bits a pixel, painted on the client.\n' +
      '-- Class per pixel: 0 plain, 1 park, 2 pavement, 3 road. Row-major from\n' +
      '-- the NORTH-WEST corner, which is world (-half, -half) -- +z is south.\n' +
      '-- Roblox cannot ship an image without uploading it as an asset, so the\n' +
      '-- map travels as pixels and becomes an EditableImage at runtime.') +
  'return {\n' +
  `\tpx = ${CO.minimap.px},\n` +
  `\thalfStuds = ${R(half)},\n` +
  `\tstudsPerPixel = ${R(2 * half / CO.minimap.px)},\n` +
  `\tbits = "${CO.minimap.bits}",\n` +
  '}\n');

/* ---------------- incident sites ---------------- */
writeFileSync(`${ROOT}/ReplicatedStorage/Shared/Sites.luau`,
  HDR('Buildings an incident can happen at -- reachable by road, evenly spread.\n' +
      '-- Studs. name is the OSM name where there is one, for the dispatch card.') +
  'return {\n' +
  CO.sites.map(s2 =>
    `\t{ x = ${R(s2.x * S)}, z = ${R(s2.y * S)}, h = ${R(s2.h * S)}, name = ${JSON.stringify(s2.name)} },`
  ).join('\n') +
  '\n}\n');

/* ---------------- depots ---------------- */
writeFileSync(`${ROOT}/ReplicatedStorage/Shared/Depots.luau`,
  HDR('Where a shift can be signed on, from OSM amenity tags.') +
  'return {\n' +
  CO.depots.map(d =>
    `\t{ kind = "${d.kind}", x = ${R(d.x * S)}, z = ${R(d.y * S)}, name = ${JSON.stringify(d.name)} },`
  ).join('\n') +
  '\n}\n');

console.log(`emit: ${CONFIG.studsPerM} studs/m, ${L.kind}, ${R(L.size * S)} studs a cell, ${R(LVS)} studs a level`);
console.log(`  ${index.length} chunk files, ${emitted} visual boxes`);
console.log(`  ${CO.boxes.length} collision boxes`);
console.log(`  district ${R(2 * half)} x ${R(2 * half)} studs, max radius ${R(Math.hypot(half, half))}`);
console.log(`  precision headroom ${(10000 / Math.hypot(half, half)).toFixed(1)}x before Roblox starts to jitter`);
