/* STAGE 5 — Luau, laid out for Rojo.
 *
 * In:  build/chunks.json, build/collision.json
 * Out: roblox/src/**.luau
 *
 * THIS IS WHERE METRES BECOME STUDS, and it is the only place in the pipeline
 * that knows about studs at all. Everything upstream works in the game's own
 * world metres, so changing CONFIG.studsPerM is a re-run of this stage — about
 * a second — rather than a re-bake. That is worth the discipline: the scale is
 * the number most likely to be wrong on the first attempt, and it is the one
 * you can only judge by standing a car next to a building and looking.
 *
 * FLAT NUMERIC ARRAYS, NOT TABLES OF TABLES. A chunk of 340 boxes as
 * {{x=..., y=..., size=...}, ...} is roughly six times the memory of a flat
 * array of numbers in Luau, and every one of those inner tables is a separate
 * allocation the GC then has to walk. At tens of thousands of parts across a
 * hundred chunks that is the difference between a stutter on chunk load and a
 * visible freeze. Seven numbers a box, documented at the top of each file.
 *
 * Usage: node tools/roblox/5-emit.mjs
 */
import { mkdirSync, writeFileSync, rmSync } from 'node:fs';
import { CONFIG } from './config.mjs';
import { readFileSync } from 'node:fs';

const V = CONFIG.voxel;
const S = CONFIG.studsPerM;
const M = V * S;                                  // studs per voxel

const CH = JSON.parse(readFileSync(`${CONFIG.out}/chunks.json`, 'utf8'));
const CO = JSON.parse(readFileSync(`${CONFIG.out}/collision.json`, 'utf8'));

const ROOT = 'roblox/src';
const dirs = [
  `${ROOT}/ReplicatedStorage/CityVisual/ChunkData`,
  `${ROOT}/ReplicatedStorage/Shared`,
  `${ROOT}/ServerScriptService/Data`
];
/* The chunk directory is wiped, not merged into. A bake with a smaller district
   leaves the previous run's outer chunks behind otherwise, and they load — so
   the city quietly keeps a ghost ring of the old slice around the new one,
   which is a genuinely baffling thing to debug from inside Studio. */
rmSync(`${ROOT}/ReplicatedStorage/CityVisual/ChunkData`, { recursive: true, force: true });
for (const d of dirs) mkdirSync(d, { recursive: true });

const R = v => Math.round(v * 1000) / 1000;       // a thousandth of a stud
const HDR = (what) =>
  `--!strict\n-- GENERATED by tools/roblox/5-emit.mjs -- do not edit by hand.\n` +
  `-- ${what}\n-- Rebuild with: node tools/roblox/bake.mjs\n\n`;

/* ---------------- palette ---------------- */
writeFileSync(`${ROOT}/ReplicatedStorage/CityVisual/Palette.luau`,
  HDR('Every colour in the city, deduplicated. Indices are 1-based (Luau).') +
  'return {\n' +
  CH.palette.map(c => `\tColor3.fromRGB(${c[0]}, ${c[1]}, ${c[2]}),`).join('\n') +
  '\n}\n');

/* ---------------- chunks ----------------

   A box is emitted as its CENTRE and its SIZE in studs, because that is what
   Roblox wants — a Part's CFrame is its centre — and converting on the client
   for thirty thousand parts is work done once here instead of on every device
   that ever loads the game.

   Ground sits at lattice level -1, so its centre lands at -M/2: the top face of
   the ground is exactly y = 0 and buildings stand on it rather than in it. */
let emitted = 0;
const index = [];
for (const c of CH.chunks) {
  const nums = [];
  for (const [x, y, z, sx, sy, sz, col] of c.boxes) {
    nums.push(
      R((x + sx / 2) * M), R((y + sy / 2) * M), R((z + sz / 2) * M),
      R(sx * M), R(sy * M), R(sz * M),
      col + 1                                     // Luau is 1-based
    );
  }
  emitted += c.boxes.length;
  const name = `Chunk_${c.cx}_${c.cz}`;
  index.push([c.cx, c.cz, c.boxes.length]);

  /* Wrapped at seven numbers a line — one box a line — so a diff of a re-bake
     shows which boxes moved rather than one 20,000-character line changing. */
  const rows = [];
  for (let i = 0; i < nums.length; i += 7) rows.push('\t' + nums.slice(i, i + 7).join(', ') + ',');

  writeFileSync(`${ROOT}/ReplicatedStorage/CityVisual/ChunkData/${name}.luau`,
    HDR(`Chunk (${c.cx}, ${c.cz}) -- ${c.boxes.length} boxes.\n` +
        '-- Seven numbers a box: centreX, centreY, centreZ, sizeX, sizeY, sizeZ, paletteIndex.\n' +
        '-- Studs, world space, district centre at the origin.') +
    'return {\n' + rows.join('\n') + '\n}\n');
}

/* ---------------- the chunk index ---------------- */
const half = CONFIG.half * S;
writeFileSync(`${ROOT}/ReplicatedStorage/CityVisual/CityMeta.luau`,
  HDR('What the client needs before it loads a single chunk.') +
  'return {\n' +
  `\tstudsPerMetre = ${S},\n` +
  `\tvoxelStuds = ${R(M)},\n` +
  `\tchunkStuds = ${R(CONFIG.chunkVox * M)},\n` +
  `\thalfStuds = ${R(half)},\n` +
  `\tchunks = {\n` +
  index.map(([cx, cz, n]) => `\t\t{ ${cx}, ${cz}, ${n} },`).join('\n') +
  `\n\t},\n}\n`);

/* ---------------- collision ----------------

   Server-side, and the only geometry the physics engine ever sees. Six numbers
   a box; no colour, because nothing renders these. */
const cnums = [];
for (const [x, z, sx, sz, y, sy] of CO.boxes) {
  cnums.push(
    R((x + sx / 2) * M), R((y + sy / 2) * M), R((z + sz / 2) * M),
    R(sx * M), R(sy * M), R(sz * M)
  );
}
const crows = [];
for (let i = 0; i < cnums.length; i += 6) crows.push('\t' + cnums.slice(i, i + 6).join(', ') + ',');
writeFileSync(`${ROOT}/ServerScriptService/Data/Collision.luau`,
  HDR(`${CO.boxes.length} building collision boxes.\n` +
      '-- Six numbers a box: centreX, centreY, centreZ, sizeX, sizeY, sizeZ. Studs.\n' +
      '-- These are the ONLY parts with CanCollide true. The voxel shell in\n' +
      '-- ReplicatedStorage.CityVisual is decoration and never enters a broadphase.') +
  'return {\n' + crows.join('\n') + '\n}\n');

/* ---------------- the drivable mask ----------------

   Shipped as base64 and decoded in Luau with buffer.fromstring, rather than as
   twenty thousand table entries. The cell size travels with it because the
   off-road constants in the driving model are tuned against it. */
writeFileSync(`${ROOT}/ReplicatedStorage/Shared/RoadMask.luau`,
  HDR('Where the tarmac is. One bit a cell, row-major from the south-west corner.\n' +
      '-- Decode: buffer.fromstring(base64decode(M.bits)); bit i is cell (i % span, i // span).\n' +
      '-- cellStuds matches W.cell (8 m) in the browser game, so the off-road\n' +
      '-- tuning in the driving model still means what it was tuned to mean.') +
  'return {\n' +
  `\tspan = ${CO.mask.span},\n` +
  `\tcellStuds = ${R(CO.mask.cell * S)},\n` +
  `\toriginStuds = ${R(-half)},\n` +
  `\tbits = "${CO.mask.bits}",\n` +
  '}\n');

/* ---------------- depots ---------------- */
writeFileSync(`${ROOT}/ReplicatedStorage/Shared/Depots.luau`,
  HDR('Where a shift can be signed on, from OSM amenity tags.') +
  'return {\n' +
  CO.depots.map(d =>
    `\t{ kind = "${d.kind}", x = ${R(d.x * S)}, z = ${R(d.y * S)}, name = ${JSON.stringify(d.name)} },`
  ).join('\n') +
  '\n}\n');

console.log(`emit: ${CONFIG.studsPerM} studs/m, ${R(M)} studs a voxel`);
console.log(`  ${index.length} chunk files, ${emitted} visual boxes`);
console.log(`  ${CO.boxes.length} collision boxes`);
console.log(`  district ${R(2 * half)} x ${R(2 * half)} studs, max radius ${R(Math.hypot(half, half))}`);
console.log(`  precision headroom ${(10000 / Math.hypot(half, half)).toFixed(1)}x before Roblox starts to jitter`);
