/* STAGE 6 — the city as the browser draws it: extruded footprints, no lattice.
 *
 * In:  build/district.json
 * Out: roblox/src/ReplicatedStorage/CityVisual/FlatData/*.luau
 *
 * The voxel path (stages 2, 3 and 5) rasterises the city onto a lattice and
 * ships hundreds of thousands of prisms. This one ships the buildings the way
 * js/render3d.js draws them -- each one extruded from its own OSM polygon --
 * and the difference in what it costs is not marginal:
 *
 *     hex lattice, 2.5 m, windows on    252,817 parts
 *     extruded footprints                 3,038 parts
 *
 * Two meshes a building, walls and roof, because a MeshPart carries one colour
 * and the browser gives a roof its own. 1,519 buildings.
 *
 * THE ROOF TRIANGULATION IS THE GAME'S OWN. earClip() and windingOf() come out
 * of js/gl.js through gamesrc.mjs, so a courtyard block is cut into the same
 * triangles here as in the browser -- including its handling of the
 * self-intersecting footprints OSM really contains, which is a bounded loop
 * that gives up and returns a slightly wrong roof rather than hanging.
 *
 * GEOMETRY IS LOCAL, POSITION IS WORLD. A MeshPart's Size is its mesh's
 * bounding box and its CFrame puts the centre of that box somewhere -- so the
 * vertices are emitted centred on their own bounding box and the world position
 * of that centre is emitted alongside. Emitting world coordinates in the mesh
 * would give every building a bounding box the size of its distance from the
 * origin.
 *
 * Usage: node tools/roblox/6-flat.mjs
 */
import { mkdirSync, writeFileSync, rmSync } from 'node:fs';
import { readFileSync } from 'node:fs';
import { CONFIG } from './config.mjs';
import { gameSrc } from './gamesrc.mjs';

const G = gameSrc();
const S = CONFIG.studsPerM;
const D = JSON.parse(readFileSync(`${CONFIG.out}/district.json`, 'utf8'));

const ROOT = 'roblox/src/ReplicatedStorage/CityVisual';
rmSync(`${ROOT}/FlatData`, { recursive: true, force: true });
mkdirSync(`${ROOT}/FlatData`, { recursive: true });

const R = v => Math.round(v * 100) / 100;
const rgbOf = hex => (G.parseColour(hex) || [128, 128, 128]).map(v => Math.round(v));
const HDR = what =>
  `--!strict\n-- GENERATED by tools/roblox/6-flat.mjs -- do not edit by hand.\n` +
  `-- ${what}\n-- Rebuild with: node tools/roblox/bake.mjs\n\n`;

/* ---------------- the palette ---------------- */
const pal = [];
const palIx = new Map();
const colour = c => {
  const k = c.join(',');
  let i = palIx.get(k);
  if (i === undefined) { i = pal.length; palIx.set(k, i); pal.push(c); }
  return i + 1;                                   // Luau is 1-based
};

/* ---------------- what a wall is made of ----------------

 * TEXTURES, the only way Roblox offers them without an uploaded asset: its own
 * materials. proctex.js grows every surface in the browser from fractal noise;
 * here the equivalent is telling Roblox that a wall is brick rather than
 * plastic, and letting it draw the brick.
 *
 * The family is RECOVERED FROM THE COLOUR rather than re-derived from the tags.
 * buildingColours() has already picked a palette -- MAT.brick, MAT.glass,
 * MAT.stucco and so on -- and every colour it can return belongs to exactly one
 * of them, so matching the RGB back gives the material it chose without a
 * second copy of its rules to drift out of step.
 */
const MATERIAL = {
  concrete: 'Concrete', stucco: 'Plaster', sand: 'Sandstone', brick: 'Brick',
  stone: 'Slate', glass: 'Glass', metal: 'Metal', wood: 'WoodPlanks',
  white: 'Plaster', pastel: 'Plaster'
};
const ROOF_MATERIAL = {
  asphalt: 'Asphalt', gravel: 'Pebble', tile: 'Slate',
  membrane: 'Plaster', metalroof: 'Metal'
};

const matNames = [];
const matIx = new Map();
const familyOf = (rgb, table, map, fallback) => {
  const k = rgb.join(',');
  for (const fam in table)
    for (const c of table[fam])
      if (c.join(',') === k) return map[fam] || fallback;
  return fallback;
};
const material = name => {
  let i = matIx.get(name);
  if (i === undefined) { i = matNames.length; matIx.set(name, i); matNames.push(name); }
  return i + 1;
};

/* ---------------- one building ---------------- */

const GATE_LEVELS_M = CONFIG.gateH;

function build(b) {
  /* OSM ways are closed -- the last vertex repeats the first -- and a repeated
     vertex is a zero-length wall and a degenerate ear. Dropped here once rather
     than guarded against in three places downstream. */
  let pts = b.pts.map(p => ({ x: p[0], y: p[1] }));
  const n0 = pts.length;
  if (n0 > 2 &&
      Math.abs(pts[0].x - pts[n0 - 1].x) < 1e-7 &&
      Math.abs(pts[0].y - pts[n0 - 1].y) < 1e-7) pts = pts.slice(0, -1);
  if (pts.length < 3) return null;

  const tris = G.earClip(pts);
  if (!tris.length) return null;

  const h = b.h;

  // local bounding box, so the mesh sits on its own centre
  let x0 = Infinity, x1 = -Infinity, y0 = Infinity, y1 = -Infinity;
  for (const p of pts) {
    x0 = Math.min(x0, p.x); x1 = Math.max(x1, p.x);
    y0 = Math.min(y0, p.y); y1 = Math.max(y1, p.y);
  }
  const cx = (x0 + x1) / 2, cy = (y0 + y1) / 2;

  /* WINDING, so the walls face outwards. The sign of the shoelace area decides
     it for the whole polygon at once, which is the only thing that survives a
     concave edge -- a per-edge test against the centroid gets the inside of a
     courtyard backwards. The browser's own windingOf, for the same reason and
     with the same answer. */
  const wind = G.windingOf(pts);

  const verts = [];
  for (const p of pts) verts.push(R((p.x - cx) * S), R((p.y - cy) * S));

  return {
    id: b.id,
    // world centre of the mesh's bounding box, in studs
    ox: R(cx * S), oz: R(cy * S),
    h: R(h * S),
    verts,
    tris,                                        // indices into verts
    wind,
    wall: colour(b.wall),
    roof: colour(b.roof),
    wmat: material(familyOf(b.wall, G.MAT, MATERIAL, 'Concrete')),
    /* The roof colour has been through a 1.22 brightening (buildingColours
       lifts it so the top-down view does not go to mush), so it no longer
       matches its own palette entry exactly -- divide it back out before
       looking it up, or every roof comes out as the fallback. */
    rmat: material(familyOf(
      b.roof.map(v => Math.round(v / 1.22)), G.ROOFMAT, ROOF_MATERIAL, 'Concrete')),
    /* Where the archway is, so the client can leave a gap in the wall run. The
       gate travels as a line and a half-width, exactly as stage 2 has it. */
    gate: (D.gates && D.gates[b.id]) ? {
      x: R((D.gates[b.id].x - cx) * S), z: R((D.gates[b.id].y - cy) * S),
      ux: D.gates[b.id].ux, uz: D.gates[b.id].uy,
      w: R(D.gates[b.id].w * S), h: R(GATE_LEVELS_M * S)
    } : null
  };
}

/* ---------------- chunked, the same 128 m as the voxel path ---------------- */

const CH = CONFIG.chunkM * S;
const chunks = new Map();
let made = 0, dropped = 0, tris = 0, verts = 0;

for (const b of D.buildings) {
  const g = build(b);
  if (!g) { dropped++; continue; }
  made++;
  tris += g.tris.length / 3;
  verts += g.verts.length / 2;
  const k = Math.floor(g.ox / CH) + ',' + Math.floor(g.oz / CH);
  let arr = chunks.get(k);
  if (!arr) chunks.set(k, arr = []);
  arr.push(g);
}

const index = [];
for (const [k, list] of [...chunks.entries()].sort()) {
  const [cx, cz] = k.split(',').map(Number);
  const rows = list.map(g => {
    const gate = g.gate
      ? `gate = { x = ${g.gate.x}, z = ${g.gate.z}, ux = ${g.gate.ux}, uz = ${g.gate.uz}, w = ${g.gate.w}, h = ${g.gate.h} }, `
      : '';
    return `\t{ ox = ${g.ox}, oz = ${g.oz}, h = ${g.h}, wall = ${g.wall}, roof = ${g.roof}, ` +
           `wmat = ${g.wmat}, rmat = ${g.rmat}, wind = ${g.wind}, ` +
           gate +
           `v = { ${g.verts.join(', ')} }, t = { ${g.tris.join(', ')} } },`;
  });
  index.push([cx, cz, list.length]);
  writeFileSync(`${ROOT}/FlatData/Flat_${cx}_${cz}.luau`,
    HDR(`Chunk (${cx}, ${cz}) -- ${list.length} buildings.\n` +
        '-- ox/oz is the world centre of the mesh bounding box, in studs; v is the\n' +
        '-- footprint relative to it, x and z interleaved; t is the roof\n' +
        '-- triangulation as 0-based indices into v; h is the height in studs.\n' +
        '-- wind is +1 or -1 and says which way round the wall quads go.') +
    'return {\n' + rows.join('\n') + '\n}\n');
}

writeFileSync(`${ROOT}/FlatMeta.luau`,
  HDR('What the flat renderer needs before it builds a chunk.') +
  'return {\n' +
  `\tstudsPerMetre = ${S},\n` +
  `\tchunkStuds = ${R(CH)},\n` +
  `\thalfStuds = ${R(CONFIG.half * S)},\n` +
  `\tbuildings = ${made},\n` +
  `\tpalette = {\n` +
  pal.map(c => `\t\tColor3.fromRGB(${c[0]}, ${c[1]}, ${c[2]}),`).join('\n') +
  `\n\t},\n` +
  /* The materials buildingColours already chose, recovered from its own
     palettes -- see MATERIAL above. This is Roblox's only way to put a texture
     on a surface without an uploaded asset. */
  `\tmaterials = {\n` +
  matNames.map(m => `\t\tEnum.Material.${m},`).join('\n') +
  `\n\t},\n` +
  `\tchunks = {\n` +
  index.map(([cx, cz, n]) => `\t\t{ ${cx}, ${cz}, ${n} },`).join('\n') +
  `\n\t},\n}\n`);

/* ---------------- the streets, as geometry ----------------

   DRAWN, NOT PAINTED. The first version of this put the whole street network on
   one flat part as a Decal, which is compact and was wrong in a way that took
   three symptoms to spot: a top-face decal's orientation in Roblox is not
   something the bake can verify, and if it lands rotated or mirrored then the
   roads you SEE are not the roads the drivable mask knows about. The car then
   crawls on painted tarmac, runs flat out across painted grass, and hits
   buildings that are exactly where the picture says the street is. All three
   were reported, and all three are one bug.

   Ribbons cannot be wrong that way: they are built from the same centrelines
   the mask is stamped from, in world coordinates, and they are also what
   ribbon() in js/render3d.js draws.

   Three layers, lifted a few centimetres apart so they resolve rather than
   z-fight: parks lowest, then the pavement ribbon, then the tarmac on top. */
const LIFT_PARK = 0.03 * S, LIFT_KERB = 0.06 * S, LIFT_ROAD = 0.09 * S;

/* ROADS TRAVEL AS SEGMENTS, NOT TRIANGLES.
 *
 * A straight run of road is a box: width across, length along, a few
 * centimetres thick. That is one ordinary Part, with a real Roblox material on
 * it, and no mesh has to be generated at runtime to make it. Parks are polygons
 * and cannot be boxes, so those still travel as triangles -- there are few of
 * them and a triangle is two wedges.
 *
 * Five numbers a segment: the two endpoints and the width. The client works out
 * the rest, which is cheaper to ship and much cheaper to read. */
const strips = new Map();                // "cx,cz" -> { kerb: [], road: [], park: [] }
function stripFor(x, z) {
  const k = Math.floor(x / CH) + ',' + Math.floor(z / CH);
  let e = strips.get(k);
  if (!e) strips.set(k, e = { kerb: [], road: [], park: [] });
  return e;
}

function stampSegments(pts, widthM, pick) {
  const w = widthM * S;
  for (let i = 1; i < pts.length; i++) {
    const ax = pts[i - 1][0] * S, az = pts[i - 1][1] * S;
    const bx = pts[i][0] * S, bz = pts[i][1] * S;
    if (Math.hypot(bx - ax, bz - az) < 0.05) continue;   // a repeated vertex
    pick(stripFor((ax + bx) / 2, (az + bz) / 2))
      .push(R(ax), R(az), R(bx), R(bz), R(w));
  }
}

if (CONFIG.kerbs) for (const r of D.roads) stampSegments(r.pts, r.w + 6, e => e.kerb);
for (const r of D.roads) stampSegments(r.pts, r.w, e => e.road);

/* Parks are polygons, so they get the same ear clipper the roofs do, and the
   client draws each triangle as a pair of wedges. */
let parkTris = 0;
for (const pk of D.parks) {
  const pts = pk.pts.map(q => ({ x: q[0], y: q[1] }));
  if (pts.length < 3) continue;
  const tri = G.earClip(pts);
  if (!tri.length) continue;
  let cx = 0, cz = 0;
  for (const q of pts) { cx += q.x; cz += q.y; }
  cx = cx / pts.length * S; cz = cz / pts.length * S;
  const out = stripFor(cx, cz).park;
  for (let i = 0; i < tri.length; i += 3) {
    parkTris++;
    for (const k of [tri[i], tri[i + 1], tri[i + 2]])
      out.push(R(pts[k].x * S), R(pts[k].y * S));
  }
}

let segs = 0;
const ribIndex = [];
for (const [k, e] of [...strips.entries()].sort()) {
  const [cx, cz] = k.split(',').map(Number);
  const parts = [];
  for (const name of ['kerb', 'road']) {
    if (!e[name].length) continue;
    segs += e[name].length / 5;
    parts.push(`\t${name} = { ${e[name].join(', ')} },`);
  }
  if (e.park.length) parts.push(`\tpark = { ${e.park.join(', ')} },`);
  if (!parts.length) continue;
  ribIndex.push([cx, cz]);
  writeFileSync(`${ROOT}/FlatData/Street_${cx}_${cz}.luau`,
    HDR(`Streets for chunk (${cx}, ${cz}).\n` +
        '-- kerb and road: five numbers a segment -- ax, az, bx, bz, width. Each is\n' +
        '-- one flat box, so no mesh has to be generated to draw a street.\n' +
        '-- park: six numbers a triangle -- three x,z pairs, drawn as two wedges.\n' +
        '-- Studs, world space.') +
    'return {\n' + parts.join('\n') + '\n}\n');
}

writeFileSync(`${ROOT}/StreetMeta.luau`,
  HDR('Which chunks have streets, how high each layer sits, and its colour.') +
  'return {\n' +
  '\tlift = { park = ' + R(LIFT_PARK) + ', kerb = ' + R(LIFT_KERB) + ', road = ' + R(LIFT_ROAD) + ' },\n' +
  '\tcolours = {\n' +
  ['plain', 'park', 'kerb', 'road'].map(n => {
    const v = rgbOf(CONFIG.groundCol[n]);
    return `\t\t${n} = Color3.fromRGB(${v[0]}, ${v[1]}, ${v[2]}),`;
  }).join('\n') +
  '\n\t},\n' +
  '\tchunks = {\n' +
  ribIndex.map(([cx, cz]) => `\t\t{ ${cx}, ${cz} },`).join('\n') +
  '\n\t},\n}\n');

console.log(`flat: ${made} buildings in ${chunks.size} chunks (${dropped} dropped)`);
console.log(`  streets       ${segs} segments + ${parkTris} park triangles in ${ribIndex.length} chunks`);
console.log(`  roof triangles  ${tris}`);
console.log(`  wall quads      ${verts}`);
console.log(`  PARTS           ${made * 2}  (walls + roof each)`);
console.log(`  palette         ${pal.length} colours`);
