/* STAGE 6 — the city as the browser draws it: extruded footprints, no lattice.
 *
 * In:  build/district.json
 * Out: roblox/src/ReplicatedStorage/CityVisual/FlatData/*.luau
 *
 * The voxel path (stages 2, 3 and 5) rasterises the city onto a lattice and
 * ships hundreds of thousands of prisms. This one ships the buildings the way
 * js/render3d.js draws them -- each one extruded from its own OSM polygon --
 * and the difference in what it costs is not marginal:
 *
 *     hex lattice, 2.5 m, windows on    252,817 parts
 *     extruded footprints                 3,038 parts
 *
 * Two meshes a building, walls and roof, because a MeshPart carries one colour
 * and the browser gives a roof its own. 1,519 buildings.
 *
 * THE ROOF TRIANGULATION IS THE GAME'S OWN. earClip() and windingOf() come out
 * of js/gl.js through gamesrc.mjs, so a courtyard block is cut into the same
 * triangles here as in the browser -- including its handling of the
 * self-intersecting footprints OSM really contains, which is a bounded loop
 * that gives up and returns a slightly wrong roof rather than hanging.
 *
 * GEOMETRY IS LOCAL, POSITION IS WORLD. A MeshPart's Size is its mesh's
 * bounding box and its CFrame puts the centre of that box somewhere -- so the
 * vertices are emitted centred on their own bounding box and the world position
 * of that centre is emitted alongside. Emitting world coordinates in the mesh
 * would give every building a bounding box the size of its distance from the
 * origin.
 *
 * Usage: node tools/roblox/6-flat.mjs
 */
import { mkdirSync, writeFileSync, rmSync } from 'node:fs';
import { readFileSync } from 'node:fs';
import { CONFIG } from './config.mjs';
import { gameSrc } from './gamesrc.mjs';

const G = gameSrc();
const S = CONFIG.studsPerM;
const D = JSON.parse(readFileSync(`${CONFIG.out}/district.json`, 'utf8'));

const ROOT = 'roblox/src/ReplicatedStorage/CityVisual';
rmSync(`${ROOT}/FlatData`, { recursive: true, force: true });
mkdirSync(`${ROOT}/FlatData`, { recursive: true });

const R = v => Math.round(v * 100) / 100;
const rgbOf = hex => (G.parseColour(hex) || [128, 128, 128]).map(v => Math.round(v));
const HDR = what =>
  `--!strict\n-- GENERATED by tools/roblox/6-flat.mjs -- do not edit by hand.\n` +
  `-- ${what}\n-- Rebuild with: node tools/roblox/bake.mjs\n\n`;

/* ---------------- the palette ---------------- */
const pal = [];
const palIx = new Map();
const colour = c => {
  const k = c.join(',');
  let i = palIx.get(k);
  if (i === undefined) { i = pal.length; palIx.set(k, i); pal.push(c); }
  return i + 1;                                   // Luau is 1-based
};

/* ---------------- what a wall is made of ----------------

 * TEXTURES, the only way Roblox offers them without an uploaded asset: its own
 * materials. proctex.js grows every surface in the browser from fractal noise;
 * here the equivalent is telling Roblox that a wall is brick rather than
 * plastic, and letting it draw the brick.
 *
 * The family is RECOVERED FROM THE COLOUR rather than re-derived from the tags.
 * buildingColours() has already picked a palette -- MAT.brick, MAT.glass,
 * MAT.stucco and so on -- and every colour it can return belongs to exactly one
 * of them, so matching the RGB back gives the material it chose without a
 * second copy of its rules to drift out of step.
 */
const MATERIAL = {
  concrete: 'Concrete', stucco: 'Plaster', sand: 'Sandstone', brick: 'Brick',
  stone: 'Slate', glass: 'Glass', metal: 'Metal', wood: 'WoodPlanks',
  white: 'Plaster', pastel: 'Plaster'
};
const ROOF_MATERIAL = {
  asphalt: 'Asphalt', gravel: 'Pebble', tile: 'Slate',
  membrane: 'Plaster', metalroof: 'Metal'
};

const matNames = [];
const matIx = new Map();
const familyOf = (rgb, table, map, fallback) => {
  const k = rgb.join(',');
  for (const fam in table)
    for (const c of table[fam])
      if (c.join(',') === k) return map[fam] || fallback;
  return fallback;
};
const material = name => {
  let i = matIx.get(name);
  if (i === undefined) { i = matNames.length; matIx.set(name, i); matNames.push(name); }
  return i + 1;
};

/* ---------------- one building ---------------- */

const GATE_LEVELS_M = CONFIG.gateH;

function build(b) {
  /* OSM ways are closed -- the last vertex repeats the first -- and a repeated
     vertex is a zero-length wall and a degenerate ear. Dropped here once rather
     than guarded against in three places downstream. */
  let pts = b.pts.map(p => ({ x: p[0], y: p[1] }));
  const n0 = pts.length;
  if (n0 > 2 &&
      Math.abs(pts[0].x - pts[n0 - 1].x) < 1e-7 &&
      Math.abs(pts[0].y - pts[n0 - 1].y) < 1e-7) pts = pts.slice(0, -1);
  if (pts.length < 3) return null;

  const tris = G.earClip(pts);
  if (!tris.length) return null;

  const h = b.h;

  // local bounding box, so the mesh sits on its own centre
  let x0 = Infinity, x1 = -Infinity, y0 = Infinity, y1 = -Infinity;
  for (const p of pts) {
    x0 = Math.min(x0, p.x); x1 = Math.max(x1, p.x);
    y0 = Math.min(y0, p.y); y1 = Math.max(y1, p.y);
  }
  const cx = (x0 + x1) / 2, cy = (y0 + y1) / 2;

  /* WINDING, so the walls face outwards. The sign of the shoelace area decides
     it for the whole polygon at once, which is the only thing that survives a
     concave edge -- a per-edge test against the centroid gets the inside of a
     courtyard backwards. The browser's own windingOf, for the same reason and
     with the same answer. */
  const wind = G.windingOf(pts);

  const verts = [];
  for (const p of pts) verts.push(R((p.x - cx) * S), R((p.y - cy) * S));

  return {
    id: b.id,
    // world centre of the mesh's bounding box, in studs
    ox: R(cx * S), oz: R(cy * S),
    h: R(h * S),
    verts,
    tris,                                        // indices into verts
    wind,
    wall: colour(b.wall),
    roof: colour(b.roof),
    wmat: material(familyOf(b.wall, G.MAT, MATERIAL, 'Concrete')),
    /* The roof colour has been through a 1.22 brightening (buildingColours
       lifts it so the top-down view does not go to mush), so it no longer
       matches its own palette entry exactly -- divide it back out before
       looking it up, or every roof comes out as the fallback. */
    rmat: material(familyOf(
      b.roof.map(v => Math.round(v / 1.22)), G.ROOFMAT, ROOF_MATERIAL, 'Concrete')),
    /* Where the archway is, so the client can leave a gap in the wall run. The
       gate travels as a line and a half-width, exactly as stage 2 has it. */
    gate: (D.gates && D.gates[b.id]) ? {
      x: R((D.gates[b.id].x - cx) * S), z: R((D.gates[b.id].y - cy) * S),
      ux: D.gates[b.id].ux, uz: D.gates[b.id].uy,
      w: R(D.gates[b.id].w * S), h: R(GATE_LEVELS_M * S)
    } : null
  };
}

/* ---------------- chunked, the same 128 m as the voxel path ---------------- */

const CH = CONFIG.chunkM * S;
const chunks = new Map();
let made = 0, dropped = 0, tris = 0, verts = 0;

for (const b of D.buildings) {
  const g = build(b);
  if (!g) { dropped++; continue; }
  made++;
  tris += g.tris.length / 3;
  verts += g.verts.length / 2;
  const k = Math.floor(g.ox / CH) + ',' + Math.floor(g.oz / CH);
  let arr = chunks.get(k);
  if (!arr) chunks.set(k, arr = []);
  arr.push(g);
}

const index = [];
for (const [k, list] of [...chunks.entries()].sort()) {
  const [cx, cz] = k.split(',').map(Number);
  const rows = list.map(g => {
    const gate = g.gate
      ? `gate = { x = ${g.gate.x}, z = ${g.gate.z}, ux = ${g.gate.ux}, uz = ${g.gate.uz}, w = ${g.gate.w}, h = ${g.gate.h} }, `
      : '';
    return `\t{ ox = ${g.ox}, oz = ${g.oz}, h = ${g.h}, wall = ${g.wall}, roof = ${g.roof}, ` +
           `wmat = ${g.wmat}, rmat = ${g.rmat}, wind = ${g.wind}, ` +
           gate +
           `v = { ${g.verts.join(', ')} }, t = { ${g.tris.join(', ')} } },`;
  });
  index.push([cx, cz, list.length]);
  writeFileSync(`${ROOT}/FlatData/Flat_${cx}_${cz}.luau`,
    HDR(`Chunk (${cx}, ${cz}) -- ${list.length} buildings.\n` +
        '-- ox/oz is the world centre of the mesh bounding box, in studs; v is the\n' +
        '-- footprint relative to it, x and z interleaved; t is the roof\n' +
        '-- triangulation as 0-based indices into v; h is the height in studs.\n' +
        '-- wind is +1 or -1 and says which way round the wall quads go.') +
    'return {\n' + rows.join('\n') + '\n}\n');
}

writeFileSync(`${ROOT}/FlatMeta.luau`,
  HDR('What the flat renderer needs before it builds a chunk.') +
  'return {\n' +
  `\tstudsPerMetre = ${S},\n` +
  `\tchunkStuds = ${R(CH)},\n` +
  `\thalfStuds = ${R(CONFIG.half * S)},\n` +
  `\tbuildings = ${made},\n` +
  `\tpalette = {\n` +
  pal.map(c => `\t\tColor3.fromRGB(${c[0]}, ${c[1]}, ${c[2]}),`).join('\n') +
  `\n\t},\n` +
  /* The materials buildingColours already chose, recovered from its own
     palettes -- see MATERIAL above. This is Roblox's only way to put a texture
     on a surface without an uploaded asset. */
  `\tmaterials = {\n` +
  matNames.map(m => `\t\tEnum.Material.${m},`).join('\n') +
  `\n\t},\n` +
  `\tchunks = {\n` +
  index.map(([cx, cz, n]) => `\t\t{ ${cx}, ${cz}, ${n} },`).join('\n') +
  `\n\t},\n}\n`);

/* ---------------- the streets, as geometry ----------------

   DRAWN, NOT PAINTED. The first version of this put the whole street network on
   one flat part as a Decal, which is compact and was wrong in a way that took
   three symptoms to spot: a top-face decal's orientation in Roblox is not
   something the bake can verify, and if it lands rotated or mirrored then the
   roads you SEE are not the roads the drivable mask knows about. The car then
   crawls on painted tarmac, runs flat out across painted grass, and hits
   buildings that are exactly where the picture says the street is. All three
   were reported, and all three are one bug.

   Ribbons cannot be wrong that way: they are built from the same centrelines
   the mask is stamped from, in world coordinates, and they are also what
   ribbon() in js/render3d.js draws.

   Three layers, lifted a few centimetres apart so they resolve rather than
   z-fight: parks lowest, then the pavement ribbon, then the tarmac on top. */
const LIFT_PARK = 0.03 * S, LIFT_KERB = 0.06 * S, LIFT_ROAD = 0.09 * S;

const ribbons = new Map();               // "cx,cz" -> { park, kerb, road }
function layerFor(x, z) {
  const k = Math.floor(x / CH) + ',' + Math.floor(z / CH);
  let e = ribbons.get(k);
  if (!e) ribbons.set(k, e = { park: [], kerb: [], road: [] });
  return e;
}

/* One segment of a road, as a quad. The corners are the centreline offset by
   half the width along the segment's normal; consecutive segments simply
   overlap at a bend, which at these widths reads as a join and costs nothing. */
function pushQuad(out, ax, az, bx, bz, half, y) {
  const dx = bx - ax, dz = bz - az;
  const len = Math.hypot(dx, dz) || 1;
  const nx = -dz / len * half, nz = dx / len * half;
  const p1 = [ax + nx, y, az + nz], p2 = [bx + nx, y, bz + nz];
  const p3 = [bx - nx, y, bz - nz], p4 = [ax - nx, y, az - nz];
  /* Wound so the normal is +Y. Same trap as the roofs: the order that reads
     naturally faces the ground. */
  out.push(p1, p3, p2, p1, p4, p3);
}

function stampRibbon(pts, widthM, y, pick) {
  const half = widthM / 2 * S;
  for (let i = 1; i < pts.length; i++) {
    const ax = pts[i - 1][0] * S, az = pts[i - 1][1] * S;
    const bx = pts[i][0] * S, bz = pts[i][1] * S;
    pushQuad(pick(layerFor((ax + bx) / 2, (az + bz) / 2)), ax, az, bx, bz, half, y);
  }
}

if (CONFIG.kerbs) for (const r of D.roads) stampRibbon(r.pts, r.w + 6, LIFT_KERB, e => e.kerb);
for (const r of D.roads) stampRibbon(r.pts, r.w, LIFT_ROAD, e => e.road);

/* Parks are polygons, so they get the same ear clipper the roofs do. */
for (const pk of D.parks) {
  const pts = pk.pts.map(q => ({ x: q[0], y: q[1] }));
  if (pts.length < 3) continue;
  const tri = G.earClip(pts);
  if (!tri.length) continue;
  let cx = 0, cz = 0;
  for (const q of pts) { cx += q.x; cz += q.y; }
  cx = cx / pts.length * S; cz = cz / pts.length * S;
  const out = layerFor(cx, cz).park;
  for (let i = 0; i < tri.length; i += 3) {
    // reversed for +Y, as with the roofs
    for (const k of [tri[i + 2], tri[i + 1], tri[i]])
      out.push([pts[k].x * S, LIFT_PARK, pts[k].y * S]);
  }
}

let ribTris = 0;
const ribIndex = [];
for (const [k, e] of [...ribbons.entries()].sort()) {
  const [cx, cz] = k.split(',').map(Number);
  const parts = [];
  for (const name of ['park', 'kerb', 'road']) {
    if (!e[name].length) continue;
    ribTris += e[name].length / 3;
    parts.push(`\t\t${name} = { ` +
      e[name].map(v => `${R(v[0])}, ${R(v[1])}, ${R(v[2])}`).join(', ') + ' },');
  }
  if (!parts.length) continue;
  ribIndex.push([cx, cz]);
  writeFileSync(`${ROOT}/FlatData/Street_${cx}_${cz}.luau`,
    HDR(`Street ribbons for chunk (${cx}, ${cz}).\n` +
        '-- Flat triangle soup, three numbers a vertex, three vertices a triangle,\n' +
        '-- already wound for a +Y normal. Studs, world space.') +
    'return {\n' + parts.join('\n') + '\n}\n');
}

writeFileSync(`${ROOT}/StreetMeta.luau`,
  HDR('Which chunks have street ribbons, and what colour each layer is.') +
  'return {\n' +
  '\tcolours = {\n' +
  ['plain', 'park', 'kerb', 'road'].map(n => {
    const v = rgbOf(CONFIG.groundCol[n]);
    return `\t\t${n} = Color3.fromRGB(${v[0]}, ${v[1]}, ${v[2]}),`;
  }).join('\n') +
  '\n\t},\n' +
  '\tchunks = {\n' +
  ribIndex.map(([cx, cz]) => `\t\t{ ${cx}, ${cz} },`).join('\n') +
  '\n\t},\n}\n');

/* ---------------- the ground, as one painted surface ----------------

   THE OTHER HALF OF "NO CUBES". The voxel path lays the streets as a layer of
   prisms -- 89,000 cells of them. Drawn the way the browser draws it, the
   ground is a SURFACE: one flat part with a picture of the roads on it.

   The picture is rasterised here and painted into an EditableImage on the
   client, the same as the minimap and for the same reason -- Roblox cannot ship
   an image without uploading it as an asset. 1024 across 1,200 m is 1.17 m a
   pixel, so a residential street is seven pixels wide and an arterial fifteen.

   Two bits a pixel: plain / park / pavement / road. 256 kB, against 3 MB as
   RGB, and four classes are all a ground plane has. */
const GPX = 1024;
const g = new Uint8Array(GPX * GPX);
const H = CONFIG.half;
const gPx = m => Math.floor((m + H) / (2 * H) * GPX);
const gM = p => (p + 0.5) / GPX * (2 * H) - H;

function gPoly(pts, v) {
  let a0 = Infinity, a1 = -Infinity, b0 = Infinity, b1 = -Infinity;
  for (const q of pts) {
    a0 = Math.min(a0, q[0]); a1 = Math.max(a1, q[0]);
    b0 = Math.min(b0, q[1]); b1 = Math.max(b1, q[1]);
  }
  for (let j = Math.max(0, gPx(b0)); j <= Math.min(GPX - 1, gPx(b1)); j++)
    for (let i = Math.max(0, gPx(a0)); i <= Math.min(GPX - 1, gPx(a1)); i++) {
      // even-odd, inline: this runs over a million cells
      let hit = false;
      const x = gM(i), y = gM(j);
      for (let m = 0, k = pts.length - 1; m < pts.length; k = m++) {
        const yi = pts[m][1], yj = pts[k][1];
        if ((yi > y) !== (yj > y)) {
          const t = (y - yi) / (yj - yi);
          if (x < pts[m][0] + t * (pts[k][0] - pts[m][0])) hit = !hit;
        }
      }
      if (hit) g[j * GPX + i] = v;
    }
}

function gLine(pts, width, v) {
  const rad = width / 2;
  const ppm = GPX / (2 * H);
  const reach = Math.ceil(rad * ppm) + 1;
  for (let s2 = 1; s2 < pts.length; s2++) {
    const [ax, ay] = pts[s2 - 1], [bx, by] = pts[s2];
    const len = Math.hypot(bx - ax, by - ay);
    const steps = Math.max(1, Math.ceil(len * ppm));
    for (let k = 0; k <= steps; k++) {
      const t = k / steps, px = ax + (bx - ax) * t, py = ay + (by - ay) * t;
      const gi = gPx(px), gj = gPx(py);
      for (let j = gj - reach; j <= gj + reach; j++)
        for (let i = gi - reach; i <= gi + reach; i++) {
          if (i < 0 || i >= GPX || j < 0 || j >= GPX) continue;
          if (Math.hypot(gM(i) - px, gM(j) - py) <= rad) g[j * GPX + i] = v;
        }
    }
  }
}

for (const p of D.parks) gPoly(p.pts, 1);
if (CONFIG.kerbs) for (const r of D.roads) gLine(r.pts, r.w + 6, 2);
for (const r of D.roads) gLine(r.pts, r.w, 3);

const gPacked = Buffer.alloc(g.length / 4);
for (let i = 0; i < g.length; i++) gPacked[i >> 2] |= (g[i] & 3) << ((i & 3) * 2);

const GC = CONFIG.groundCol;
const rgb = rgbOf;
writeFileSync(`${ROOT}/GroundTex.luau`,
  HDR('The ground as a picture: two bits a pixel, painted on the client.\n' +
      '-- 0 plain, 1 park, 2 pavement, 3 road. Row-major from world (-half, -half).') +
  'return {\n' +
  `\tpx = ${GPX},\n` +
  `\thalfStuds = ${R(CONFIG.half * S)},\n` +
  '\tpalette = {\n' +
  [GC.plain, GC.park, GC.kerb, GC.road]
    .map(c => { const v = rgb(c); return `\t\tColor3.fromRGB(${v[0]}, ${v[1]}, ${v[2]}),`; })
    .join('\n') +
  '\n\t},\n' +
  `\tbits = "${gPacked.toString('base64')}",\n` +
  '}\n');

let groundRoad = 0;
for (const v of g) if (v === 3) groundRoad++;

console.log(`flat: ${made} buildings in ${chunks.size} chunks (${dropped} dropped)`);
console.log(`  street ribbons ${ribTris} triangles in ${ribIndex.length} chunks`);
console.log(`  ground        ${GPX}x${GPX} at ${(2 * H / GPX).toFixed(2)} m a pixel, ${(100 * groundRoad / g.length).toFixed(1)}% road, ${(gPacked.length / 1024).toFixed(0)} kB`);
console.log(`  roof triangles  ${tris}`);
console.log(`  wall quads      ${verts}`);
console.log(`  MESHPARTS       ${made * 2}  (walls + roof each)`);
console.log(`  palette         ${pal.length} colours`);
