/* STAGE 7 — the things that live in the city: the road graph, the solid mask,
 * and the trees.
 *
 * In:  build/district.json
 * Out: roblox/src/ReplicatedStorage/Shared/RoadNet.luau
 *      roblox/src/ReplicatedStorage/Shared/SolidMask.luau
 *      roblox/src/ReplicatedStorage/CityVisual/TreeMeta.luau
 *      roblox/src/ReplicatedStorage/CityVisual/FlatData/Tree_<cx>_<cz>.luau
 *
 * WHY THE ROAD GRAPH SHIPS AT ALL. Stage 4 already bakes a drivable MASK, and
 * the driving model is happy with it: "is there tarmac under this point" is the
 * only question a car being steered by a human ever asks. A car being steered
 * by nothing needs the opposite thing -- not a picture of where the roads are
 * but the roads themselves, as polylines it can walk along, because that is
 * what js/game.js:updateTraffic follows and what js/entities.js:pedWalkPoint
 * offsets from. A mask cannot answer "which way is this street going".
 *
 * IT IS SMALL ENOUGH TO SHIP WHOLE, unlike the city it describes. On the 2.4 km
 * district: 2,271 drivable ways, 10,425 points and 14,616 junction
 * continuations, about 600 kB of Luau. The buildings alone are 179,401 Parts
 * and have to be streamed; the graph is read by the traffic wherever the
 * traffic is, so it is loaded whole and stays that way.
 *
 * THE TREES ARE CHUNKED, THOUGH, on the same 128 m grid as the buildings, and
 * for the same reason: 16,372 Parts is not something to build all at once.
 *
 * IN METRES, NOT STUDS, and that is deliberate for the same reason the rest of
 * the pipeline is: the traffic runs on VehicleModel, VehicleModel is the
 * browser's drive() in metres and seconds, and every constant in it was tuned
 * against a road network measured in metres. The studs conversion happens once,
 * when a car is placed, exactly as it does for the player.
 *
 * Usage: node tools/roblox/7-life.mjs
 */
import { writeFileSync } from 'node:fs';
import { readFileSync } from 'node:fs';
import { CONFIG } from './config.mjs';
import { gameSrc, hash01 } from './gamesrc.mjs';

const G = gameSrc();
const S = CONFIG.studsPerM;
const D = JSON.parse(readFileSync(`${CONFIG.out}/district.json`, 'utf8'));

const SHARED = 'roblox/src/ReplicatedStorage/Shared';
const VISUAL = 'roblox/src/ReplicatedStorage/CityVisual';

const R = v => Math.round(v * 100) / 100;
const rgbOf = hex => (G.parseColour(hex) || [128, 128, 128]).map(v => Math.round(v));
const HDR = what =>
  `--!strict\n-- GENERATED by tools/roblox/7-life.mjs -- do not edit by hand.\n` +
  `-- ${what}\n-- Rebuild with: node tools/roblox/bake.mjs\n\n`;

/* ================================================================ the graph */

/* Only the drivable ways. Footways and tracks are DRAWN by stage 6 -- they are
   part of what the city looks like -- but nothing drives down them, and a
   pedestrian way in the traffic graph is a car on a footpath. Two of the 690
   are dropped by this. */
const ways = D.roads.filter(r => r.drive && r.pts.length >= 2);

/* THE BUCKET GRID, which is W.dbuckets in js/world.js under another name.

   roadPoint() picks a random segment within a band of the player and would
   otherwise be a scan of every segment in the district on every spawn -- 2,830
   of them, several times a second, for as long as somebody is driving fast
   enough to keep outrunning the traffic. The browser learnt this the hard way
   at skeleton scale (see driveSegsNear) and the fix is the same one.

   120 m cells: big enough that the 220 m spawn ring touches a handful of them
   rather than dozens, small enough that a cell is not most of the district. */
const CELL = 120;
const bucket = new Map();
const bkey = (gx, gy) => gx * 8192 + gy;

let segCount = 0;
ways.forEach((r, wi) => {
  for (let i = 0; i + 1 < r.pts.length; i++) {
    const a = r.pts[i], b = r.pts[i + 1];
    /* Registered in EVERY cell the segment crosses, not just the one its
       midpoint lands in. A 300 m arterial leg whose midpoint is in one cell is
       invisible from both of its ends otherwise, which is how you get a spawn
       ring that reliably finds nothing on the long straight streets and only
       ever fills up the fiddly ones. */
    const gx0 = Math.floor(Math.min(a[0], b[0]) / CELL), gx1 = Math.floor(Math.max(a[0], b[0]) / CELL);
    const gy0 = Math.floor(Math.min(a[1], b[1]) / CELL), gy1 = Math.floor(Math.max(a[1], b[1]) / CELL);
    for (let gx = gx0; gx <= gx1; gx++) for (let gy = gy0; gy <= gy1; gy++) {
      const k = bkey(gx, gy);
      let arr = bucket.get(k);
      if (!arr) bucket.set(k, arr = []);
      arr.push(wi + 1, i + 1);            // 1-based: Luau arrays start at 1
    }
    segCount++;
  }
});

/* ---------------- the junctions ----------------

   WITHOUT THIS, EVERY CAR DOES A U-TURN EVERY FIVE SECONDS.

   updateTraffic in the browser has one answer for running out of road: turn
   round and drive back. That is fine there because nothing else was ever built,
   and it is very much not fine here, because of what the data actually looks
   like once you measure it:

       688 drivable ways, 4.1 nodes each, mean length 62 m
       92% of way ENDS sit within a metre of a node of another way

   OSM splits a street at every junction, so a "way" is one block. A car that
   reverses at the end of one is a car that reverses at every junction — and a
   U-turn on an eight metre street is a car swinging through the pavement and
   into the building behind it. Measured in the Node harness before this
   existed: median lane-tracking error 0.76 m, p90 7.9 m, and every one of 53
   cars clipped a footprint at some point in ninety seconds.

   So each way end carries the continuations available at it. Three numbers a
   link — the way to join, the node to join it at, and which way along it to
   travel. The direction of travel there is NOT baked, though the first version
   did bake it: it is two more numbers on every one of 4,436 links, which is 90
   kB of Luau, and the runtime derives it from two nodes it is already holding.
   A junction is taken about sixteen times a second across the whole fleet;
   this is not a hot path and does not deserve to be denormalised.

   ENDS ONLY, NOT MID-WAY TURNS. A car joins another street where its own
   street stops, which is what a block-per-way network means. It does not turn
   off half way down one. */
const JGRID = 1.0;                         // metres: how close counts as joined
const jkey = (x, y) => `${Math.round(x / JGRID)},${Math.round(y / JGRID)}`;

/* Every node of every drivable way, bucketed by position, so a way end can find
   what it touches — including the INTERIOR node of another way, which is what a
   T junction is. */
const jnodes = new Map();
ways.forEach((r, wi) => {
  r.pts.forEach((p, n) => {
    const k = jkey(p[0], p[1]);
    let a = jnodes.get(k);
    if (!a) jnodes.set(k, a = []);
    a.push([wi, n + 1]);                   // 1-based node index, for Luau
  });
});

/* The unit direction of travel leaving node `n` of way `r` in direction `dir`,
   or null where there is no next node that way. */
function leaveDir(r, n, dir) {
  const j = n + dir;
  if (j < 1 || j > r.pts.length) return null;
  const a = r.pts[n - 1], b = r.pts[j - 1];
  const L = Math.hypot(b[0] - a[0], b[1] - a[1]);
  if (L < 1e-6) return null;
  return [(b[0] - a[0]) / L, (b[1] - a[1]) / L];
}

let linkCount = 0, deadEnds = 0;
const linkLines = [];
ways.forEach((r, wi) => {
  const N = r.pts.length;
  const per = [];
  for (const endNode of [1, N]) {
    const p = r.pts[endNode - 1];
    const out = [];
    /* The nine cells around it, because a point a hair over the rounding
       boundary from its neighbour is the commonest way a junction is missed. */
    const gx = Math.round(p[0] / JGRID), gy = Math.round(p[1] / JGRID);
    for (let dx = -1; dx <= 1; dx++) for (let dy = -1; dy <= 1; dy++) {
      const a = jnodes.get(`${gx + dx},${gy + dy}`);
      if (!a) continue;
      for (const [oi, on] of a) {
        if (oi === wi) continue;           // its own end, and its own other end
        const q = ways[oi].pts[on - 1];
        if (Math.hypot(q[0] - p[0], q[1] - p[1]) > JGRID) continue;
        for (const dir of [1, -1]) {
          const u = leaveDir(ways[oi], on, dir);
          if (!u) continue;                // that end of that way has nowhere to go
          out.push(oi + 1, on, dir);
        }
      }
    }
    if (!out.length) deadEnds++;
    linkCount += out.length / 3;
    per.push(`[${endNode}] = { ${out.join(', ')} },`);
  }
  /* Keyed by the NODE the car ran off, so the runtime looks up the end it
     actually reached rather than working out which one that was. */
  linkLines.push(`\t\t[${wi + 1}] = { ${per.join(' ')} },`);
});

/* Way length, precomputed: roadPoint's `minLen` filter asks for it on every
   attempt and it never changes. */
const wayLen = r => {
  let L = 0;
  for (let i = 1; i < r.pts.length; i++)
    L += Math.hypot(r.pts[i][0] - r.pts[i - 1][0], r.pts[i][1] - r.pts[i - 1][1]);
  return L;
};

const wayLines = ways.map(r =>
  `\t\t{ w = ${R(r.w)}, len = ${R(wayLen(r))}, oneway = ${r.oneway ? 'true' : 'false'}, ` +
  `pts = { ${r.pts.map(p => `${R(p[0])}, ${R(p[1])}`).join(', ')} } },`);

const bucketLines = [...bucket.entries()].sort((a, b) => a[0] - b[0])
  .map(([k, arr]) => `\t\t[${k}] = { ${arr.join(', ')} },`);

writeFileSync(`${SHARED}/RoadNet.luau`,
  HDR('The drivable road network as polylines, in METRES, +x east +y south --\n' +
      '-- the same coordinates VehicleModel drives in.\n' +
      '--\n' +
      '-- ways[i].pts is a flat list: x1, y1, x2, y2, ... so a node n is at\n' +
      '-- pts[n*2-1], pts[n*2] with n counting from 1.\n' +
      '--\n' +
      '-- buckets maps floor(x/cell)*8192 + floor(y/cell) to a flat list of\n' +
      '-- (way, segment) pairs, both 1-based. A segment appears in every cell it\n' +
      '-- crosses, so a long straight is findable from either end.\n' +
      '--\n' +
      '-- links[way][endNode] is where a car can go when it runs off that end:\n' +
      '-- three numbers a continuation -- the way to join, the node to join it at,\n' +
      '-- and which way along to travel (1 or -1). Empty means a genuine dead end,\n' +
      '-- and only then does a car turn round.') +
  'return {\n' +
  `\tcell = ${CELL},\n` +
  '\tways = {\n' + wayLines.join('\n') + '\n\t},\n' +
  '\tbuckets = {\n' + bucketLines.join('\n') + '\n\t},\n' +
  '\tlinks = {\n' + linkLines.join('\n') + '\n\t},\n' +
  '}\n');

/* ============================================================ the solid mask */

/* Buildings, rasterised to one bit a cell, so a walker can ask "is there a wall
   here" without a spatial query. Scan-converted per polygon rather than
   sampled: sampling a cell centre misses a building narrower than a cell, and a
   3 m cell against real Belgrade footprints misses plenty of them. */
const SC = CONFIG.solidCell;
const SSPAN = Math.ceil(2 * CONFIG.half / SC);
const SORIGIN = -CONFIG.half;
const solid = new Uint8Array(SSPAN * SSPAN);
const sset = (i, j) => {
  if (i >= 0 && i < SSPAN && j >= 0 && j < SSPAN) solid[j * SSPAN + i] = 1;
};

/* Even-odd scanline fill of a polygon given in metres. The same rule parseOSM's
   own footprints are drawn under, and it handles the concave courtyard blocks
   this district is full of. */
function fillPoly(pts) {
  let minY = Infinity, maxY = -Infinity;
  for (const p of pts) { if (p[1] < minY) minY = p[1]; if (p[1] > maxY) maxY = p[1]; }
  const j0 = Math.max(0, Math.floor((minY - SORIGIN) / SC));
  const j1 = Math.min(SSPAN - 1, Math.floor((maxY - SORIGIN) / SC));
  const xs = [];
  for (let j = j0; j <= j1; j++) {
    const y = SORIGIN + (j + 0.5) * SC;
    xs.length = 0;
    for (let k = 0, n = pts.length; k < n; k++) {
      const a = pts[k], b = pts[(k + 1) % n];
      if ((a[1] > y) === (b[1] > y)) continue;
      xs.push(a[0] + (y - a[1]) / (b[1] - a[1]) * (b[0] - a[0]));
    }
    xs.sort((p, q) => p - q);
    for (let k = 0; k + 1 < xs.length; k += 2) {
      const i0 = Math.max(0, Math.floor((xs[k] - SORIGIN) / SC));
      const i1 = Math.min(SSPAN - 1, Math.floor((xs[k + 1] - SORIGIN) / SC));
      for (let i = i0; i <= i1; i++) sset(i, j);
    }
  }
}
for (const b of D.buildings) fillPoly(b.pts);

const solidPacked = Buffer.alloc(Math.ceil(solid.length / 8));
for (let i = 0; i < solid.length; i++) if (solid[i]) solidPacked[i >> 3] |= 1 << (i & 7);

writeFileSync(`${SHARED}/SolidMask.luau`,
  HDR('Where a building is. One bit a cell, row-major from the south-west corner.\n' +
      '-- Decode: buffer.fromstring(base64decode(M.bits)); bit i is cell (i % span, i // span).\n' +
      '-- Metres, because the only caller is the pedestrian walk and that runs in metres.') +
  'return {\n' +
  `\tspan = ${SSPAN},\n` +
  `\tcellM = ${SC},\n` +
  `\toriginM = ${SORIGIN},\n` +
  `\tbits = "${solidPacked.toString('base64')}",\n` +
  '}\n');

/* ================================================================== the trees */

/* Rejection needs two questions answered a few thousand times: is this point in
   a building, and is it on tarmac. The solid mask answers the first at 3 m,
   which is too coarse when the thing being rejected is a 1 m trunk against a
   wall -- so buildings are tested EXACTLY, against their own polygons, through
   a bounding-box grid. Roads are tested exactly too, against half the real
   carriageway width, because that is the number the ribbons are drawn from and
   a tree in the road is the one placement nobody will forgive. */
const GRID = 40;
const gkey = (gx, gy) => gx * 8192 + gy;

const bldGrid = new Map();
for (const b of D.buildings) {
  const [x0, y0, x1, y1] = b.bb;
  for (let gx = Math.floor(x0 / GRID); gx <= Math.floor(x1 / GRID); gx++)
    for (let gy = Math.floor(y0 / GRID); gy <= Math.floor(y1 / GRID); gy++) {
      const k = gkey(gx, gy);
      let a = bldGrid.get(k);
      if (!a) bldGrid.set(k, a = []);
      a.push(b);
    }
}

const segGrid = new Map();
for (const r of D.roads) {
  for (let i = 1; i < r.pts.length; i++) {
    const a = r.pts[i - 1], b = r.pts[i];
    const half = r.w * 0.5;
    const gx0 = Math.floor((Math.min(a[0], b[0]) - half) / GRID);
    const gx1 = Math.floor((Math.max(a[0], b[0]) + half) / GRID);
    const gy0 = Math.floor((Math.min(a[1], b[1]) - half) / GRID);
    const gy1 = Math.floor((Math.max(a[1], b[1]) + half) / GRID);
    for (let gx = gx0; gx <= gx1; gx++) for (let gy = gy0; gy <= gy1; gy++) {
      const k = gkey(gx, gy);
      let arr = segGrid.get(k);
      if (!arr) segGrid.set(k, arr = []);
      arr.push([a, b, half]);
    }
  }
}

const inPoly = (pts, x, y) => {
  let inside = false;
  for (let i = 0, j = pts.length - 1; i < pts.length; j = i++) {
    const a = pts[i], b = pts[j];
    if ((a[1] > y) !== (b[1] > y) &&
        x < (b[0] - a[0]) * (y - a[1]) / (b[1] - a[1]) + a[0]) inside = !inside;
  }
  return inside;
};

const inBuilding = (x, y) => {
  const arr = bldGrid.get(gkey(Math.floor(x / GRID), Math.floor(y / GRID)));
  if (!arr) return false;
  for (const b of arr) {
    const [x0, y0, x1, y1] = b.bb;
    if (x < x0 || x > x1 || y < y0 || y > y1) continue;
    if (inPoly(b.pts, x, y)) return true;
  }
  return false;
};

/* Distance to the nearest carriageway edge, negative when inside one. `pad` is
   how much daylight a trunk wants beyond the tarmac. */
const onRoad = (x, y, pad) => {
  const arr = segGrid.get(gkey(Math.floor(x / GRID), Math.floor(y / GRID)));
  if (!arr) return false;
  for (const [a, b, half] of arr) {
    const ex = b[0] - a[0], ey = b[1] - a[1];
    const L2 = ex * ex + ey * ey;
    if (L2 < 1e-9) continue;
    let t = ((x - a[0]) * ex + (y - a[1]) * ey) / L2;
    t = t < 0 ? 0 : t > 1 ? 1 : t;
    const dx = x - (a[0] + ex * t), dy = y - (a[1] + ey * t);
    if (dx * dx + dy * dy < (half + pad) * (half + pad)) return true;
  }
  return false;
};

/* And no two trunks in the same place. Same grid trick, built as we go. */
const treeGrid = new Map();
const MIN_GAP = CONFIG.treeMinGapM;
const tooClose = (x, y) => {
  const gx = Math.floor(x / GRID), gy = Math.floor(y / GRID);
  for (let i = -1; i <= 1; i++) for (let j = -1; j <= 1; j++) {
    const arr = treeGrid.get(gkey(gx + i, gy + j));
    if (!arr) continue;
    for (const p of arr)
      if ((p[0] - x) ** 2 + (p[1] - y) ** 2 < MIN_GAP * MIN_GAP) return true;
  }
  return false;
};

const trees = [];
let rejBuilding = 0, rejRoad = 0, rejGap = 0, rejEdge = 0;

/* THE SPECIES, AND WHAT DECIDES IT. A tree is a trunk and a canopy, and the
   only things that vary are the canopy's shape, its colour and how big the
   whole thing is. Everything comes out of hash01 of the rounded position, so a
   tree is a pure function of where it stands: no counter, no sequence, nothing
   that shifts when a placement earlier in the loop is rejected. */
function plant(x, y, kind) {
  if (x < -CONFIG.half || x > CONFIG.half || y < -CONFIG.half || y > CONFIG.half) { rejEdge++; return false; }
  if (inBuilding(x, y)) { rejBuilding++; return false; }
  if (onRoad(x, y, 0.9)) { rejRoad++; return false; }
  if (tooClose(x, y)) { rejGap++; return false; }

  const seed = Math.round(x * 10) * 7919 + Math.round(y * 10);
  const r1 = hash01(seed, 3), r2 = hash01(seed, 11), r3 = hash01(seed, 29);
  /* One in six is a conifer, and only in the parks -- a spruce on a Belgrade
     pavement is not a thing, and the point of the second species is that a park
     does not read as a hedge planted in rows. */
  const conifer = kind === 'park' && r3 < 0.17;
  const h = conifer ? 6.5 + r1 * 5.5 : 5.5 + r1 * 4.5;      // metres, trunk to crown
  const spread = conifer ? h * 0.30 : h * (0.52 + r2 * 0.20);
  const bare = conifer ? h * 0.16 : h * (0.36 + r2 * 0.10);  // trunk below the canopy

  const k = gkey(Math.floor(x / GRID), Math.floor(y / GRID));
  let arr = treeGrid.get(k);
  if (!arr) treeGrid.set(k, arr = []);
  arr.push([x, y]);

  /* Emitted in STUDS, because unlike the traffic nothing about a tree is ever
     integrated -- it is placed once and never moves, so the conversion may as
     well happen in the bake and save the client the multiply. */
  trees.push([R(x * S), R(y * S), R(h * S), R(spread * S), R(bare * S),
              conifer ? 2 : (r3 < 0.5 ? 0 : 1)]);
  return true;
}

/* ---- street trees: along the verge, both sides ---- */
const VERGE_CLASSES = new Set(CONFIG.treeRoadClass);
if (CONFIG.trees) {
  const EVERY = CONFIG.treeStreetEveryM;
  for (const r of D.roads) {
    if (!VERGE_CLASSES.has(r.cls)) continue;
    const off = r.w * 0.5 + CONFIG.treeVergeM;
    /* Walked at a fixed spacing along the whole polyline rather than per node:
       OSM nodes are where the street BENDS, not where the planting is, so
       node-spaced trees cluster at every corner and leave the straights empty. */
    let carry = EVERY * hash01(r.id || 1, 5);        // where this street starts counting
    for (let i = 1; i < r.pts.length; i++) {
      const a = r.pts[i - 1], b = r.pts[i];
      const ex = b[0] - a[0], ey = b[1] - a[1];
      const L = Math.hypot(ex, ey);
      if (L < 1e-6) continue;
      const ux = ex / L, uy = ey / L;
      for (let s = carry; s < L; s += EVERY) {
        const px = a[0] + ux * s, py = a[1] + uy * s;
        for (const side of [-1, 1]) plant(px - uy * off * side, py + ux * off * side, 'street');
      }
      carry = (carry - L) % EVERY;
      if (carry < 0) carry += EVERY;
    }
  }

  /* ---- park trees: a jittered lattice inside the polygon ---- */
  const SP = CONFIG.treeParkSpacingM;
  for (const pk of D.parks) {
    if (pk.pts.length < 3) continue;
    let x0 = Infinity, y0 = Infinity, x1 = -Infinity, y1 = -Infinity;
    for (const p of pk.pts) {
      if (p[0] < x0) x0 = p[0]; if (p[0] > x1) x1 = p[0];
      if (p[1] < y0) y0 = p[1]; if (p[1] > y1) y1 = p[1];
    }
    for (let gx = Math.floor(x0 / SP); gx <= Math.ceil(x1 / SP); gx++) {
      for (let gy = Math.floor(y0 / SP); gy <= Math.ceil(y1 / SP); gy++) {
        /* Jittered, not on the lattice: a park planted on an exact grid reads
           as an orchard, and Kalemegdan is not an orchard. Two thirds of a cell
           of jitter is enough to break the rows and little enough that the
           spacing still holds. */
        const jx = (hash01(gx * 131 + gy, 41) - 0.5) * SP * 0.66;
        const jy = (hash01(gx * 131 + gy, 67) - 0.5) * SP * 0.66;
        const x = gx * SP + jx, y = gy * SP + jy;
        if (!inPoly(pk.pts, x, y)) continue;
        plant(x, y, 'park');
      }
    }
  }
}

/* CHUNKED ON THE SAME 128 m GRID AS EVERYTHING ELSE, so the trees stream with
   the buildings and the streets rather than all 8,186 of them arriving at once
   whatever the client is doing. Same key, same file naming, same index shape --
   there is one streamer on the client and it should not need to know that trees
   are a different kind of thing. */
const TCH = CONFIG.chunkM * S;
const treeChunks = new Map();
for (const t of trees) {
  const k = Math.floor(t[0] / TCH) + ',' + Math.floor(t[1] / TCH);
  let arr = treeChunks.get(k);
  if (!arr) treeChunks.set(k, arr = []);
  arr.push(t);
}
const treeIndex = [];
for (const [k, list] of [...treeChunks.entries()].sort()) {
  const [cx, cz] = k.split(',').map(Number);
  treeIndex.push([cx, cz, list.length]);
  writeFileSync(`${VISUAL}/FlatData/Tree_${cx}_${cz}.luau`,
    HDR(`Trees for chunk (${cx}, ${cz}) -- ${list.length} of them.\n` +
        '-- Six numbers each, in STUDS and world space:\n' +
        '--   x, z, height, canopy spread, bare trunk below the canopy, form\n' +
        '-- form: 0 and 1 are broadleaves in two greens, 2 is a conifer.') +
    'return {\n' + list.map(t => `\t{ ${t.join(', ')} },`).join('\n') + '\n}\n');
}

const colOf = n => rgbOf(CONFIG.treeCol[n]);
writeFileSync(`${VISUAL}/TreeMeta.luau`,
  HDR('Which chunks have trees in them, and what colour a tree is.\n' +
      '-- The trees themselves are in FlatData/Tree_<cx>_<cz>.luau, chunked on the\n' +
      '-- same grid as the buildings so one streamer handles all three.\n' +
      '-- Placed against the real footprints and the real carriageway widths at\n' +
      '-- bake time, so nothing needs checking at runtime.') +
  'return {\n' +
  '\tcolours = {\n' +
  ['trunk', 'leafA', 'leafB', 'conifer'].map(n => {
    const v = colOf(n);
    return `\t\t${n} = Color3.fromRGB(${v[0]}, ${v[1]}, ${v[2]}),`;
  }).join('\n') +
  '\n\t},\n' +
  '\tchunks = {\n' +
  treeIndex.map(([cx, cz, n]) => `\t\t{ ${cx}, ${cz}, ${n} },`).join('\n') +
  '\n\t},\n}\n');

/* ==================================================================== report */

let solidCells = 0;
for (const v of solid) if (v) solidCells++;
const forms = [0, 0, 0];
for (const t of trees) forms[t[5]]++;

console.log(`life: road graph ${ways.length} ways, ${segCount} segments, ${bucket.size} buckets at ${CELL} m`);
console.log(`  junctions     ${linkCount} continuations across ${ways.length * 2} way ends, ` +
            `${deadEnds} of them dead (${(100 * deadEnds / (ways.length * 2)).toFixed(0)}%)`);
console.log(`  solid mask    ${SSPAN} x ${SSPAN} at ${SC} m, ${solidCells} solid cells ` +
            `(${(100 * solidCells / solid.length).toFixed(1)}%), ${solidPacked.length} bytes`);
console.log(`  trees         ${trees.length}  (${forms[0] + forms[1]} broadleaf, ${forms[2]} conifer) ` +
            `-> ${trees.length * 2} parts in ${treeChunks.size} chunks`);
console.log(`  rejected      ${rejBuilding} in a building, ${rejRoad} on tarmac, ` +
            `${rejGap} too close, ${rejEdge} outside the district`);
